### ISSUE TITLE
QoR value calculation

### ISSUE THREAD

**Issue by nikhilkevinjones** [NYU-MLDA/OpenABC#12]
Hi,

I am working through your paper and code, it appears that you in the QoR prediction task, you use QoR label that is generally between -3 and +3 and it captures the number of nodes in an AIG. However, it is not clear to me how do you get the labels from that information. Could you please clarify.

Thanks,
Nikhil

**Comment by animeshbchowdhury** [comment]
Hi @nikhilkevinjones,

We perform a technique called label normalization per IP/design before training the QoR prediction model. As part of training data, the designs are synthesized using synthesis recipes and number of nodes post synthesis are obtained. Then, we perform standard normalization per design (not the entire training dataset) to obtain normalized node count which we use as label. Now, a value which is -3 typically indicates that a synthesis recipe is good for a particular design because it resulted in lesser node count (than the average) whereas a +3 indicates the recipe is bad.

Now, this predictor can be used as evaluator in any black-box optimization methods like simulated annealing to explore the search space of synthesis recipes optimizing for lesser node counts.

Let me know if this clarifies your doubt.

**Comment by nikhilkevinjones** [comment]
Hi,

Okay, thank you. Is there a reason for normalization between-3 and +3, would it make a difference if the normalization was between -1 and +1?

BR,
Nikhil

**Comment by animeshbchowdhury** [comment]
Hi,

I have used the standard normalization which is 0-1 (0 mean 1 variance) which resulted in most of the values within -3 to +3. You can always go for other normalization techniques like min-max, where you would end up having 0 as minimum and 1 as maximum value.

**Comment by nikhilkevinjones** [comment]
Hi Animesh,

Thank you for the clarification.

Regards,
Nikhil
